### STAGE 1: Build ###
FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

### STAGE 2: Run ###
FROM nginx:stable-alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/conf.d/ /etc/nginx/conf.d/

# Monta los certificados SSL
COPY /etc/letsencrypt/ /etc/letsencrypt/

# Exponer los puertos necesarios
EXPOSE 80
EXPOSE 443