### POST
POST http://localhost:8080/usuario/nueva_pregunta HTTP/1.1
Content-Type: application/json

{
    "nombre": "Sergio",
    "apellido": "Canté",
    "correo": "s.cante.2ddb@gmcil.com",
    "edad": "17",
    "pregunta": "¿para que sirve el pap?"
}